version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:latest
    ports:
      - 8080:8080
    environment:
      - DB_ADDR=db
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  
  db:
    image: postgres
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
